import os
import time
import math
import select
import sys

# Motor model
class BLDCMotor:
    def __init__(self, R=0.1, L=0.001, Ke=0.01, Kt=0.01, J=0.0001, b=0.00001, v_supply=12.0):
        self.R = R  # Resistance (Ohms)
        self.L = L  # Inductance (Henries)
        self.Ke = Ke  # Back-EMF constant (V/(rad/s))
        self.Kt = Kt  # Torque constant (Nm/A)
        self.J = J  # Rotor inertia (kg*m^2)
        self.b = b  # Viscous friction coefficient (Nms)
        self.v_supply = v_supply

        self.theta = 0.0  # Rotor position (radians)
        self.omega = 0.0  # Rotor angular velocity (rad/s)
        self.current = 0.0  # Phase current (Amps)

    def update(self, v_applied, dt, load_torque=0.0, friction_coeff=None):
        if friction_coeff is not None:
            self.b = friction_coeff

        # Electrical equation: V = I*R + L*di/dt + Ke*omega
        di_dt = (v_applied - self.current * self.R - self.Ke * self.omega) / self.L
        self.current += di_dt * dt

        # Mechanical equation: T_motor = Kt*I
        # J*domega/dt = T_motor - b*omega - T_load
        torque_motor = self.Kt * self.current
        domega_dt = (torque_motor - self.b * self.omega - load_torque) / self.J
        self.omega += domega_dt * dt
        self.theta += self.omega * dt

    def get_hall_state(self):
        angle_deg = (self.theta * (180.0 / math.pi)) % 360.0
        if 0 <= angle_deg < 60:    return (1, 0, 1)
        if 60 <= angle_deg < 120:   return (1, 0, 0)
        if 120 <= angle_deg < 180:  return (1, 1, 0)
        if 180 <= angle_deg < 240:  return (0, 1, 0)
        if 240 <= angle_deg < 300:  return (0, 1, 1)
        if 300 <= angle_deg < 360:  return (0, 0, 1)
        return (0, 0, 0)

def main():
    pipe_in_path = "/tmp/arduino_in"
    pipe_out_path = "/tmp/arduino_out"

    if os.path.exists(pipe_in_path): os.remove(pipe_in_path)
    if os.path.exists(pipe_out_path): os.remove(pipe_out_path)

    os.mkfifo(pipe_in_path)
    os.mkfifo(pipe_out_path)

    print("Motor Simulator started. Waiting for Arduino...")
    pipe_in = open(pipe_in_path, "r")
    pipe_out = open(pipe_out_path, "w")
    print("Arduino connected.")

    motor = BLDCMotor()
    last_time = time.time()

    pins_out = {}
    load_torque = 0.0
    friction_coeff = 0.00001

    while True:
        line = pipe_in.readline()
        if not line:
            break

        line = line.strip()
        if line.startswith("P"):
            try:
                p_idx = line.find('P')
                d_idx = line.find('D')
                a_idx = line.find('A')
                pin = int(line[p_idx+1:d_idx])
                d = int(line[d_idx+1:a_idx])
                a = int(line[a_idx+1:])
                pins_out[pin] = (d, a)
            except Exception:
                pass
        elif line.startswith("CMD"):
            # Format: CMD_LOAD_val, CMD_FRIC_val
            try:
                if "LOAD_" in line:
                    load_torque = float(line.split("LOAD_")[1])
                if "FRIC_" in line:
                    friction_coeff = float(line.split("FRIC_")[1])
            except Exception:
                pass
        elif line == "SYNC":
            now = time.time()
            dt = now - last_time
            if dt <= 0 or dt > 0.1: dt = 0.001
            last_time = now

            pwm = pins_out.get(9, (0, 0))[1]
            any_en = any(pins_out.get(p, (0,0))[0] == 1 for p in [5,6,7,8,10,11])
            v_applied = (pwm / 255.0) * motor.v_supply if any_en or 9 in pins_out else 0.0

            # Simple regenerative braking model: if PWM is 0 and any EN is HIGH,
            # we might have a short circuit (braking) depending on the bridge state.
            # In speed_control_extra_regen, extra regen turns on ALL HIGH side FETs.
            # If all AH, BH, CH are HIGH and AL, BL, CL are LOW, it's a short circuit.
            all_high_on = all(pins_out.get(p, (0,0))[0] == 1 for p in [5,7,10])
            all_low_off = all(pins_out.get(p, (0,0))[0] == 0 for p in [6,8,11])
            if all_high_on and all_low_off:
                # Short circuit braking
                v_applied = 0.0
                # current will be generated by Back-EMF: I = (V_back - 0) / R
                # but we'll let the physics update handle it if we set v_applied = 0.

            motor.update(v_applied, dt, load_torque, friction_coeff)
            hall = motor.get_hall_state()

            curr_adc = int(abs(motor.current) * 10)
            spd_target = pins_out.get(15, (0, 600))[1] # Keep last speed target or default
            omega_adc = int(abs(motor.omega) * 10)

            out_str = f"I2D{hall[0]}A0\n"
            out_str += f"I3D{hall[1]}A0\n"
            out_str += f"I4D{hall[2]}A0\n"
            out_str += f"I8D{hall[0]}A0\n"
            out_str += f"I12D{hall[1]}A0\n"
            out_str += f"I13D{hall[2]}A0\n"
            out_str += f"I14D0A{curr_adc}\n"
            out_str += f"I15D0A{spd_target}\n"
            out_str += f"I9D0A{omega_adc}\n"
            out_str += "ACK\n"

            pipe_out.write(out_str)
            pipe_out.flush()

if __name__ == "__main__":
    main()
